services:
  db:
    container_name: database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  server:
    container_name: server
    restart: always
    build:
      context: .
    depends_on:
      - db
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - server
